server:
  port: 8085
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sample_devops_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://172.17.0.3:3306/sample_devops_db?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx#EDC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update