server:
  port: 8085
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sample_devops_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://devops_sample_db:3306/sample_devops_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update